# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharvil
email: sharvil.popli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Database Developer - Open-Source Enthusiast - Problem Solver
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://sharvi1.com" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"

# Social media profiles - feel free to add more here
twitter_username: shrezyp
github_username:  sharvi1
#facebook_username: sharvilp
instagram_username: livrash
stackoverflow_url: http://stackoverflow.com/users/6379562/sharvil-popli
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://au.linkedin.com/in/sharvilp

# Address information
address_street: 
address_city: Chadstone
address_state: VIC
address_zip: 3148

# Build settings
markdown: kramdown
